### ISSUE TITLE
Submission form updates

### ISSUE THREAD

**Issue by JodiNA** [SFDO-Community-Sprints/sprintys-community-resources#16]
- Modifying the "Description" question to be more clear about what to write
- Adding explanatory language about how duplicates are treated
- Adding explanatory language about the curation/editing of submissions

**Comment by JodiNA** [comment]
Current (original) submission page language:
Your resource has been successfully submitted. One of the Sprinty's Community Resources team will review the resource and put it up on the site.



Thank for you contributing to this community! Feel free to submit another resource (or more)! Just use the button below.

**Comment by JodiNA** [comment]
Changes to description.

Original:

New:
![image](https://github.com/SFDO-Community-Sprints/sprintys-community-resources/assets/8515331/84d5c930-fbde-4d4f-b66c-f19529201c46)

**Comment by chericodes** [comment]
Suggest —

1. Remove exclamation point from headline (one is in subject, one is in line below)
2. Headline: consider changing "submitting" to "contributing"
3. See updated Resource Submitted text below (reflects email template)
4. FORM: Remove "Please" from the Description label — start with "Describe" (otherwise the text looks good)

UPDATED CONFIRMATION TEXT —

**Thank you for contributing a resource**

Your resource has been successfully submitted. Thank you for contributing to this community.

The curation team will review your submission, and you will receive an email once your resource has been published. Please note: we may edit your text to improve clarity or enhance searchability.

Curation is done on a monthly basis. If you have questions, reach out to us at our [Trailblazer Community Group](https://trailhead.salesforce.com/trailblazer-community/groups/0F94S000000kQ1NSAU). If you'd like to contribute more resources, just click the button below.

With appreciation,
The Sprinty's Community Resources Team

**Comment by JodiNA** [comment]
Revised confirmation page as per @chericodes's notes:
![image](https://github.com/SFDO-Community-Sprints/sprintys-community-resources/assets/8515331/8f108a42-4a9e-44eb-87d8-466b544e219e)

Cheri - I also removed "please" from a few other field labels. :-)
